### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xbanks**
Formatted some of the tables for easier readability. Not sure I got the program-lane mapping correct in the MultiLaneLocker example, I'd be happy to fix with the correct version if provided.

### CODE REVIEW

**Comment by adrianfilip** [comment]
Thanks @xbanks. The new formatting looks awesome.

The laning should be changed a bit though. In both cases it should look like this:
P1 should be on L1 and L3
P2 on L1
P3 on L2 and L4
P4 on L1 and L2

**Comment by adrianfilip** [comment]
@xbanks Please let me know if I should make the changes.

**Comment by xbanks** [comment]
Ok, I think I've fixed the laning

**Comment by adrianfilip** [comment]
@xbanks That covers it. Thanks for the formatting.

**Pull request merged**
